// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'counterState_test.dart' as counterState_test;

void main() {
  counterState_test.main();
}
