name: ajwah_bloc_test
version: 0.1.1+1
homepage: https://github.com/JUkhan/ajwah_bloc_dart
description: A Dart package that makes testing ajwah_bloc easy.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0
  test: ^1.16.0

dev_dependencies:
  ajwah_bloc:
