name: ajwah_bloc_test
version: 0.1.1+1
homepage: https://github.com/JUkhan/ajwah_bloc_dart
description: A Dart package that makes testing ajwah_bloc easy.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  test: ">=1.6.3 <3.0.0"
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.6.6
  build_test: ^0.10.7+3
  dartdoc: ^0.28.3+2
  test_coverage: ^0.2.3
  ajwah_bloc:
