name: flutter_ajwah_bloc
version: 0.1.0
homepage: https://github.com/JUkhan/ajwah_bloc_dart
description: A Dart package that makes easy to develop flutter app using BlocProvider and SingleStateConsumer.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ajwah_bloc:
    path: ../ajwah_bloc
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
