// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'controller_test.dart' as controller_test;
import 'counter2_test.dart' as counter2_test;

void main() {
  counter2_test.main();
  controller_test.main();
}
