// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'action_filter_test.dart' as action_filter_test;
import 'ajwah_store_test.dart' as ajwah_store_test;

void main() {
  ajwah_store_test.main();
  action_filter_test.main();
}
