// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'controller_test.dart' as controller_test;

void main() {
  controller_test.main();
}
