name: ajwah_bloc
version: 2.0.0+3
homepage: https://github.com/JUkhan/ajwah_bloc_dart/tree/new-style
description: Rx based state management library. Manage your application's states, effects, and actions easy way. Make apps more scalable with a unidirectional data-flow.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  rxdart: ">=0.23.0 <3.0.0"
  meta: ">=1.1.7 <3.0.0"

dev_dependencies:
  test: ^1.6.3
  build_runner: ^1.6.6
  build_test: ^0.10.7+3
  dartdoc: ^0.28.3+2
  test_coverage: ^0.2.3
  pedantic: ^1.9.0
  ajwah_bloc_test:
