name: ajwah_bloc
version: 0.1.1
author: "Jasim Khan <jasim.uddin.khan@gmail.com>"
homepage: https://github.com/JUkhan/ajwah_bloc_dart
description: Rx based state management library for Dart. Manage your application's states, effects, and actions easy way.


environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  rxdart: ">=0.19.0 <2.0.0"
  meta: ">=1.0.0 <3.0.0"
  async: ">=2.0.0 <4.0.0"

dev_dependencies:
  test: ^1.6.3
  build_runner: ^1.4.0
  build_test: ^0.10.7+3
  dartdoc: ^0.28.3+2