name: ajwah_bloc
version: 2.6.6
homepage: https://github.com/JUkhan/ajwah_bloc_dart
description: A reactive state management library. Manage your application's states, effects, and actions easy way. Make apps more scalable with a unidirectional data-flow.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ">=0.25.0 <3.0.0"
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.0
  build_runner:
  build_test:
  test_coverage:
  pedantic: ^1.9.0
  ajwah_bloc_test:
